CARD_HOVER_TRANSFORM = "translateY(-4px)"

SECTION_TEXT_WIDTH = "32ch"
SECTION_MAX_WIDTH = "720px"

SONG_CARD_IMAGE_HEIGHT = "220px"

FEATURED_CARD_IMAGE_HEIGHT = {
    "base": "170px",
    "md": "220px",
    "lg": "180px",
}

SONG_HERO_IMAGE_HEIGHT = "460px"

LEARNING_ICON_SIZE = "22px"
INPUT_ICON_SIZE = "18px"

INSTRUMENT_CARD_MIN_HEIGHT = "220px"

SECTION_PADDING_Y = {
    "base": "1rem",
    "lg": "2rem",
}

HOME_HERO_MOBILE_IMAGE_HEIGHT = {
    "base": "240px",
    "sm": "280px",
}

HOME_HERO_DESKTOP_IMAGE_HEIGHT = "620px"

HOME_HERO_TEXT_MAX_WIDTH = "560px"

HOME_HERO_TEXT_MIN_WIDTH = "420px"

CARD_PADDING_LARGE = "2rem"

SECTION_PADDING_TOP = "1rem"

SECTION_PADDING_BOTTOM = "2rem"

TITLE_SIZE_CARD = "5"

TITLE_SIZE_SECTION = "6"

TITLE_SIZE_PAGE = "9"

TEXT_SIZE_SECONDARY = "3"